"""properties table

Revision ID: 3759a12f898e
Revises: a102b2d40d7b
Create Date: 2023-06-10 13:20:31.232954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3759a12f898e'
down_revision = 'a102b2d40d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('square_feet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('basement', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terrace', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('garden', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('balcony', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('balcony')
        batch_op.drop_column('garden')
        batch_op.drop_column('terrace')
        batch_op.drop_column('basement')
        batch_op.drop_column('location')
        batch_op.drop_column('square_feet')

    # ### end Alembic commands ###
